In [ ]:
from pathlib import Path
import duckdb

ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / "pyproject.toml").exists())
CSV = ROOT / "dados/raw/resultados/2026/votacao_candidato_munzona_2026/votacao_candidato_munzona_2026_BRASIL.csv"
con = duckdb.connect()
con.execute("LOAD encodings")
con.sql(f"CREATE OR REPLACE VIEW dados_raw AS SELECT * FROM read_csv('{CSV.as_posix()}', delim=';', header=true, encoding='cp1252', all_varchar=true, ignore_errors=true)")
con.sql(f"COPY dados_raw TO '{ROOT / "dados" / "processed" / "resultados.parquet"}' (FORMAT PARQUET, COMPRESSION ZSTD)")
con.sql(f"CREATE VIEW dados AS SELECT * FROM '{ROOT / "dados" / "processed" / "resultados.parquet"}'")

IOException: IO Error: No files found that match the pattern "/home/davi/Documentos/UFPI/6-periodo/BDR/analiseCandidatos/dados/raw/resultados/2024/votacao_candidato_munzona_2026/votacao_candidato_munzona_2026_BRASIL.csv"

LINE 1: CREATE OR REPLACE VIEW dados_raw AS SELECT * FROM read_csv('/home/davi/Documentos/UFPI/6-periodo/BDR/analiseC...
                                                          ^

In [ ]:
con.sql("DESCRIBE dados").df()

                   column_name column_type null   key default extra
0                   DT_GERACAO     VARCHAR  YES  None    None  None
1                   HH_GERACAO     VARCHAR  YES  None    None  None
2                  ANO_ELEICAO     VARCHAR  YES  None    None  None
3              CD_TIPO_ELEICAO     VARCHAR  YES  None    None  None
4              NM_TIPO_ELEICAO     VARCHAR  YES  None    None  None
5                     NR_TURNO     VARCHAR  YES  None    None  None
6                   CD_ELEICAO     VARCHAR  YES  None    None  None
7                   DS_ELEICAO     VARCHAR  YES  None    None  None
8                   DT_ELEICAO     VARCHAR  YES  None    None  None
9               TP_ABRANGENCIA     VARCHAR  YES  None    None  None
10                       SG_UF     VARCHAR  YES  None    None  None
11                       SG_UE     VARCHAR  YES  None    None  None
12                       NM_UE     VARCHAR  YES  None    None  None
13                CD_MUNICIPIO     VARCHAR  YES  None    None  None
14                NM_MUNICIPIO     VARCHAR  YES  None    None  None
15                     NR_ZONA     VARCHAR  YES  None    None  None
16                    CD_CARGO     VARCHAR  YES  None    None  None
17                    DS_CARGO     VARCHAR  YES  None    None  None
18                SQ_CANDIDATO     VARCHAR  YES  None    None  None
19                NR_CANDIDATO     VARCHAR  YES  None    None  None
20                NM_CANDIDATO     VARCHAR  YES  None    None  None
21           NM_URNA_CANDIDATO     VARCHAR  YES  None    None  None
22         NM_SOCIAL_CANDIDATO     VARCHAR  YES  None    None  None
23     CD_SITUACAO_CANDIDATURA     VARCHAR  YES  None    None  None
24     DS_SITUACAO_CANDIDATURA     VARCHAR  YES  None    None  None
25    CD_DETALHE_SITUACAO_CAND     VARCHAR  YES  None    None  None
26    DS_DETALHE_SITUACAO_CAND     VARCHAR  YES  None    None  None
27      CD_SITUACAO_JULGAMENTO     VARCHAR  YES  None    None  None
28      DS_SITUACAO_JULGAMENTO     VARCHAR  YES  None    None  None
29        CD_SITUACAO_CASSACAO     VARCHAR  YES  None    None  None
30        DS_SITUACAO_CASSACAO     VARCHAR  YES  None    None  None
31  CD_SITUACAO_DCONST_DIPLOMA     VARCHAR  YES  None    None  None
32  DS_SITUACAO_DCONST_DIPLOMA     VARCHAR  YES  None    None  None
33               TP_AGREMIACAO     VARCHAR  YES  None    None  None
34                  NR_PARTIDO     VARCHAR  YES  None    None  None
35                  SG_PARTIDO     VARCHAR  YES  None    None  None
36                  NM_PARTIDO     VARCHAR  YES  None    None  None
37                NR_FEDERACAO     VARCHAR  YES  None    None  None
38                NM_FEDERACAO     VARCHAR  YES  None    None  None
39                SG_FEDERACAO     VARCHAR  YES  None    None  None
40     DS_COMPOSICAO_FEDERACAO     VARCHAR  YES  None    None  None
41                SQ_COLIGACAO     VARCHAR  YES  None    None  None
42                NM_COLIGACAO     VARCHAR  YES  None    None  None
43     DS_COMPOSICAO_COLIGACAO     VARCHAR  YES  None    None  None
44         ST_VOTO_EM_TRANSITO     VARCHAR  YES  None    None  None
45           QT_VOTOS_NOMINAIS     VARCHAR  YES  None    None  None
46    NM_TIPO_DESTINACAO_VOTOS     VARCHAR  YES  None    None  None
47   QT_VOTOS_NOMINAIS_VALIDOS     VARCHAR  YES  None    None  None
48            CD_SIT_TOT_TURNO     VARCHAR  YES  None    None  None
49            DS_SIT_TOT_TURNO     VARCHAR  YES  None    None  None

In [ ]:
con.sql("SUMMARIZE dados").df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,DT_GERACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
1,HH_GERACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
2,ANO_ELEICAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
3,CD_TIPO_ELEICAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
4,NM_TIPO_ELEICAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
5,NR_TURNO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
6,CD_ELEICAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
7,DS_ELEICAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
8,DT_ELEICAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
9,TP_ABRANGENCIA,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
10,SG_UF,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
11,SG_UE,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
12,NM_UE,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
13,CD_MUNICIPIO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
14,NM_MUNICIPIO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
15,NR_ZONA,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
16,CD_CARGO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
17,DS_CARGO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
18,SQ_CANDIDATO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
19,NR_CANDIDATO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
20,NM_CANDIDATO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
21,NM_URNA_CANDIDATO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
22,NM_SOCIAL_CANDIDATO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
23,CD_SITUACAO_CANDIDATURA,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
24,DS_SITUACAO_CANDIDATURA,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
25,CD_DETALHE_SITUACAO_CAND,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
26,DS_DETALHE_SITUACAO_CAND,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
27,CD_SITUACAO_JULGAMENTO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
28,DS_SITUACAO_JULGAMENTO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
29,CD_SITUACAO_CASSACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
30,DS_SITUACAO_CASSACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
31,CD_SITUACAO_DCONST_DIPLOMA,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
32,DS_SITUACAO_DCONST_DIPLOMA,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
33,TP_AGREMIACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
34,NR_PARTIDO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
35,SG_PARTIDO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
36,NM_PARTIDO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
37,NR_FEDERACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
38,NM_FEDERACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
39,SG_FEDERACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
40,DS_COMPOSICAO_FEDERACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
41,SQ_COLIGACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
42,NM_COLIGACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
43,DS_COMPOSICAO_COLIGACAO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
44,ST_VOTO_EM_TRANSITO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
45,QT_VOTOS_NOMINAIS,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
46,NM_TIPO_DESTINACAO_VOTOS,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
47,QT_VOTOS_NOMINAIS_VALIDOS,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
48,CD_SIT_TOT_TURNO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN
49,DS_SIT_TOT_TURNO,VARCHAR,None,None,0,<NA>,<NA>,<NA>,<NA>,<NA>,0,NaN

In [ ]:
con.sql("EXPLAIN SELECT * FROM dados").df()

     explain_key                                      explain_value
0  physical_plan  ┌───────────────────────────┐\n│        PARQUE...

In [ ]:
con.sql("SHOW ALL TABLES")

┌──────────┬─────────┬───────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┐
│ database │ schema  │   name    │                                                                                                                                                                                                                                                                                                                                                                                                                                column_names                                                                                                                                                                                                                                                                                                                                                                                                                                 │                                                                                                                                                                                                                            column_types                                                                                                                                                                                                                            │ temporary │
│ varchar  │ varchar │  varchar  │                                                                                                                                                                                                                                                                                                                                                                                                                                  varchar[]                                                                                                                                                                                                                                                                                                                                                                                                                                  │                                                                                                                                                                                                                             varchar[]                                                                                                                                                                                                                              │  boolean  │
├──────────┼─────────┼───────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┤
│ memory   │ main    │ dados     │ [DT_GERACAO, HH_GERACAO, ANO_ELEICAO, CD_TIPO_ELEICAO, NM_TIPO_ELEICAO, NR_TURNO, CD_ELEICAO, DS_ELEICAO, DT_ELEICAO, TP_ABRANGENCIA, SG_UF, SG_UE, NM_UE, CD_MUNICIPIO, NM_MUNICIPIO, NR_ZONA, CD_CARGO, DS_CARGO, SQ_CANDIDATO, NR_CANDIDATO, NM_CANDIDATO, NM_URNA_CANDIDATO, NM_SOCIAL_CANDIDATO, CD_SITUACAO_CANDIDATURA, DS_SITUACAO_CANDIDATURA, CD_DETALHE_SITUACAO_CAND, DS_DETALHE_SITUACAO_CAND, CD_SITUACAO_JULGAMENTO, DS_SITUACAO_JULGAMENTO, CD_SITUACAO_CASSACAO, DS_SITUACAO_CASSACAO, CD_SITUACAO_DCONST_DIPLOMA, DS_SITUACAO_DCONST_DIPLOMA, TP_AGREMIACAO, NR_PARTIDO, SG_PARTIDO, NM_PARTIDO, NR_FEDERACAO, NM_FEDERACAO, SG_FEDERACAO, DS_COMPOSICAO_FEDERACAO, SQ_COLIGACAO, NM_COLIGACAO, DS_COMPOSICAO_COLIGACAO, ST_VOTO_EM_TRANSITO, QT_VOTOS_NOMINAIS, NM_TIPO_DESTINACAO_VOTOS, QT_VOTOS_NOMINAIS_VALIDOS, CD_SIT_TOT_TURNO, DS_SIT_TOT_TURNO] │ [VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR] │ false     │
│ memory   │ main    │ dados_raw │ [DT_GERACAO, HH_GERACAO, ANO_ELEICAO, CD_TIPO_ELEICAO, NM_TIPO_ELEICAO, NR_TURNO, CD_ELEICAO, DS_ELEICAO, DT_ELEICAO, TP_ABRANGENCIA, SG_UF, SG_UE, NM_UE, CD_MUNICIPIO, NM_MUNICIPIO, NR_ZONA, CD_CARGO, DS_CARGO, SQ_CANDIDATO, NR_CANDIDATO, NM_CANDIDATO, NM_URNA_CANDIDATO, NM_SOCIAL_CANDIDATO, CD_SITUACAO_CANDIDATURA, DS_SITUACAO_CANDIDATURA, CD_DETALHE_SITUACAO_CAND, DS_DETALHE_SITUACAO_CAND, CD_SITUACAO_JULGAMENTO, DS_SITUACAO_JULGAMENTO, CD_SITUACAO_CASSACAO, DS_SITUACAO_CASSACAO, CD_SITUACAO_DCONST_DIPLOMA, DS_SITUACAO_DCONST_DIPLOMA, TP_AGREMIACAO, NR_PARTIDO, SG_PARTIDO, NM_PARTIDO, NR_FEDERACAO, NM_FEDERACAO, SG_FEDERACAO, DS_COMPOSICAO_FEDERACAO, SQ_COLIGACAO, NM_COLIGACAO, DS_COMPOSICAO_COLIGACAO, ST_VOTO_EM_TRANSITO, QT_VOTOS_NOMINAIS, NM_TIPO_DESTINACAO_VOTOS, QT_VOTOS_NOMINAIS_VALIDOS, CD_SIT_TOT_TURNO, DS_SIT_TOT_TURNO] │ [VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR] │ false     │
└──────────┴─────────┴───────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┘

In [ ]:
con.sql("SELECT DISTINCT DT_GERACAO FROM dados").df()

Empty DataFrame
Columns: [DT_GERACAO]
Index: []