In [22]:
from pathlib import Path

import duckdb

ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / "pyproject.toml").exists())
CSV = ROOT / "dados/raw/abstencao/2024/comparecimento_abstencao_2024/perfil_comparecimento_abstencao_2024_BRASIL.csv"
con = duckdb.connect()
con.execute("LOAD encodings")
con.sql(
    f"CREATE OR REPLACE VIEW dados_raw AS SELECT * FROM read_csv('{CSV.as_posix()}', delim=';', header=true, encoding='cp1252', all_varchar=true, ignore_errors=true)"
)
con.sql(f"COPY dados_raw TO '{ROOT / 'dados' / 'processed' / 'abstencao.parquet'}' (FORMAT PARQUET, COMPRESSION ZSTD)")
con.sql(f"CREATE VIEW dados AS SELECT * FROM '{ROOT / 'dados' / 'processed' / 'abstencao.parquet'}'")

In [23]:
con.sql("DESCRIBE dados").df()

                      column_name column_type null   key default extra
0                      DT_GERACAO     VARCHAR  YES  None    None  None
1                      HH_GERACAO     VARCHAR  YES  None    None  None
2                     ANO_ELEICAO     VARCHAR  YES  None    None  None
3                        NR_TURNO     VARCHAR  YES  None    None  None
4                           SG_UF     VARCHAR  YES  None    None  None
5                    CD_MUNICIPIO     VARCHAR  YES  None    None  None
6                    NM_MUNICIPIO     VARCHAR  YES  None    None  None
7                         NR_ZONA     VARCHAR  YES  None    None  None
8                       CD_GENERO     VARCHAR  YES  None    None  None
9                       DS_GENERO     VARCHAR  YES  None    None  None
10                CD_ESTADO_CIVIL     VARCHAR  YES  None    None  None
11                DS_ESTADO_CIVIL     VARCHAR  YES  None    None  None
12                CD_FAIXA_ETARIA     VARCHAR  YES  None    None  None
13                DS_FAIXA_ETARIA     VARCHAR  YES  None    None  None
14           CD_GRAU_ESCOLARIDADE     VARCHAR  YES  None    None  None
15           DS_GRAU_ESCOLARIDADE     VARCHAR  YES  None    None  None
16                    CD_COR_RACA     VARCHAR  YES  None    None  None
17                    DS_COR_RACA     VARCHAR  YES  None    None  None
18                  CD_QUILOMBOLA     VARCHAR  YES  None    None  None
19                  DS_QUILOMBOLA     VARCHAR  YES  None    None  None
20           CD_INTERPRETE_LIBRAS     VARCHAR  YES  None    None  None
21           DS_INTERPRETE_LIBRAS     VARCHAR  YES  None    None  None
22           CD_IDENTIDADE_GENERO     VARCHAR  YES  None    None  None
23           DS_IDENTIDADE_GENERO     VARCHAR  YES  None    None  None
24             CD_IDIOMA_INDIGENA     VARCHAR  YES  None    None  None
25             DS_IDIOMA_INDIGENA     VARCHAR  YES  None    None  None
26              CD_GRUPO_INDIGENA     VARCHAR  YES  None    None  None
27              DS_GRUPO_INDIGENA     VARCHAR  YES  None    None  None
28                       QT_APTOS     VARCHAR  YES  None    None  None
29              QT_COMPARECIMENTO     VARCHAR  YES  None    None  None
30                   QT_ABSTENCAO     VARCHAR  YES  None    None  None
31  QT_COMPARECIMENTO_DEFICIENCIA     VARCHAR  YES  None    None  None
32       QT_ABSTENCAO_DEFICIENCIA     VARCHAR  YES  None    None  None
33          QT_COMPARECIMENTO_TTE     VARCHAR  YES  None    None  None
34               QT_ABSTENCAO_TTE     VARCHAR  YES  None    None  None
35        QT_COMPAREC_FACULTATIVO     VARCHAR  YES  None    None  None
36            QT_ABST_FACULTATIVO     VARCHAR  YES  None    None  None
37        QT_COMPAREC_OBRIGATORIO     VARCHAR  YES  None    None  None
38            QT_ABST_OBRIGATORIO     VARCHAR  YES  None    None  None
39  QT_COMPAREC_DEFIC_FACULTATIVO     VARCHAR  YES  None    None  None
40      QT_ABST_DEFIC_FACULTATIVO     VARCHAR  YES  None    None  None
41  QT_COMPAREC_DEFIC_OBRIGATORIO     VARCHAR  YES  None    None  None
42      QT_ABST_DEFIC_OBRIGATORIO     VARCHAR  YES  None    None  None

In [24]:
con.sql("SUMMARIZE dados").df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,DT_GERACAO,VARCHAR,29/04/2025,29/04/2025,1,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
1,HH_GERACAO,VARCHAR,16:22:43,16:22:43,1,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
2,ANO_ELEICAO,VARCHAR,2024,2024,1,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
3,NR_TURNO,VARCHAR,1,2,2,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
4,SG_UF,VARCHAR,AC,TO,27,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
5,CD_MUNICIPIO,VARCHAR,00019,99074,4534,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
6,NM_MUNICIPIO,VARCHAR,ABADIA DE GOIÁS,ÓLEO,5976,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
7,NR_ZONA,VARCHAR,1,99,396,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
8,CD_GENERO,VARCHAR,0,4,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
9,DS_GENERO,VARCHAR,FEMININO,NÃO INFORMADO,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
10,CD_ESTADO_CIVIL,VARCHAR,0,9,5,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
11,DS_ESTADO_CIVIL,VARCHAR,CASADO,VIÚVO,6,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
12,CD_FAIXA_ETARIA,VARCHAR,-3,9999,22,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
13,DS_FAIXA_ETARIA,VARCHAR,100 anos ou mais,Inválido,24,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
14,CD_GRAU_ESCOLARIDADE,VARCHAR,0,8,10,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
15,DS_GRAU_ESCOLARIDADE,VARCHAR,ANALFABETO,SUPERIOR INCOMPLETO,10,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
16,CD_COR_RACA,VARCHAR,-1,5,6,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
17,DS_COR_RACA,VARCHAR,Amarela,Preta,6,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
18,CD_QUILOMBOLA,VARCHAR,-1,2,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
19,DS_QUILOMBOLA,VARCHAR,NÃO,SIM,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
20,CD_INTERPRETE_LIBRAS,VARCHAR,-1,2,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
21,DS_INTERPRETE_LIBRAS,VARCHAR,NÃO,SIM,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
22,CD_IDENTIDADE_GENERO,VARCHAR,-1,3,4,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
23,DS_IDENTIDADE_GENERO,VARCHAR,Cisgênero,Transgênero,4,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
24,CD_IDIOMA_INDIGENA,VARCHAR,-1,2,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
25,DS_IDIOMA_INDIGENA,VARCHAR,NÃO,SIM,3,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
26,CD_GRUPO_INDIGENA,VARCHAR,-1,99,275,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
27,DS_GRUPO_INDIGENA,VARCHAR,Aconã,Zuruahã,291,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
28,QT_APTOS,VARCHAR,1,999,3476,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
29,QT_COMPARECIMENTO,VARCHAR,0,999,3117,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
30,QT_ABSTENCAO,VARCHAR,0,999,1479,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
31,QT_COMPARECIMENTO_DEFICIENCIA,VARCHAR,0,99,133,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
32,QT_ABSTENCAO_DEFICIENCIA,VARCHAR,0,99,98,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
33,QT_COMPARECIMENTO_TTE,VARCHAR,0,9,55,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
34,QT_ABSTENCAO_TTE,VARCHAR,0,8,10,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
35,QT_COMPAREC_FACULTATIVO,VARCHAR,0,996,741,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
36,QT_ABST_FACULTATIVO,VARCHAR,0,99,546,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
37,QT_COMPAREC_OBRIGATORIO,VARCHAR,0,999,3117,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
38,QT_ABST_OBRIGATORIO,VARCHAR,0,999,1479,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
39,QT_COMPAREC_DEFIC_FACULTATIVO,VARCHAR,0,91,119,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
40,QT_ABST_DEFIC_FACULTATIVO,VARCHAR,0,95,98,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
41,QT_COMPAREC_DEFIC_OBRIGATORIO,VARCHAR,0,99,108,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0
42,QT_ABST_DEFIC_OBRIGATORIO,VARCHAR,0,99,56,<NA>,<NA>,<NA>,<NA>,<NA>,9825477,0.0

In [25]:
con.sql("EXPLAIN SELECT * FROM dados").df()

     explain_key                                      explain_value
0  physical_plan  ┌───────────────────────────┐\n│        PARQUE...

In [26]:
con.sql("SHOW ALL TABLES")

┌──────────┬─────────┬───────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────┐
│ database │ schema  │   name    │                                                                                                                                                                                                                                                                                                                                                                                                         column_names                                                                                                                                                                                                                                                                                                                                                                                                         │                                                                                                                                                                                            column_types                                                                                                                                                                                             │ temporary │
│ varchar  │ varchar │  varchar  │                                                                                                                                                                                                                                                                                                                                                                                                          varchar[]                                                                                                                                                                                                                                                                                                                                                                                                           │                                                                                                                                                                                              varchar[]                                                                                                                                                                                              │  boolean  │
├──────────┼─────────┼───────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────┤
│ memory   │ main    │ dados     │ [DT_GERACAO, HH_GERACAO, ANO_ELEICAO, NR_TURNO, SG_UF, CD_MUNICIPIO, NM_MUNICIPIO, NR_ZONA, CD_GENERO, DS_GENERO, CD_ESTADO_CIVIL, DS_ESTADO_CIVIL, CD_FAIXA_ETARIA, DS_FAIXA_ETARIA, CD_GRAU_ESCOLARIDADE, DS_GRAU_ESCOLARIDADE, CD_COR_RACA, DS_COR_RACA, CD_QUILOMBOLA, DS_QUILOMBOLA, CD_INTERPRETE_LIBRAS, DS_INTERPRETE_LIBRAS, CD_IDENTIDADE_GENERO, DS_IDENTIDADE_GENERO, CD_IDIOMA_INDIGENA, DS_IDIOMA_INDIGENA, CD_GRUPO_INDIGENA, DS_GRUPO_INDIGENA, QT_APTOS, QT_COMPARECIMENTO, QT_ABSTENCAO, QT_COMPARECIMENTO_DEFICIENCIA, QT_ABSTENCAO_DEFICIENCIA, QT_COMPARECIMENTO_TTE, QT_ABSTENCAO_TTE, QT_COMPAREC_FACULTATIVO, QT_ABST_FACULTATIVO, QT_COMPAREC_OBRIGATORIO, QT_ABST_OBRIGATORIO, QT_COMPAREC_DEFIC_FACULTATIVO, QT_ABST_DEFIC_FACULTATIVO, QT_COMPAREC_DEFIC_OBRIGATORIO, QT_ABST_DEFIC_OBRIGATORIO] │ [VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR] │ false     │
│ memory   │ main    │ dados_raw │ [DT_GERACAO, HH_GERACAO, ANO_ELEICAO, NR_TURNO, SG_UF, CD_MUNICIPIO, NM_MUNICIPIO, NR_ZONA, CD_GENERO, DS_GENERO, CD_ESTADO_CIVIL, DS_ESTADO_CIVIL, CD_FAIXA_ETARIA, DS_FAIXA_ETARIA, CD_GRAU_ESCOLARIDADE, DS_GRAU_ESCOLARIDADE, CD_COR_RACA, DS_COR_RACA, CD_QUILOMBOLA, DS_QUILOMBOLA, CD_INTERPRETE_LIBRAS, DS_INTERPRETE_LIBRAS, CD_IDENTIDADE_GENERO, DS_IDENTIDADE_GENERO, CD_IDIOMA_INDIGENA, DS_IDIOMA_INDIGENA, CD_GRUPO_INDIGENA, DS_GRUPO_INDIGENA, QT_APTOS, QT_COMPARECIMENTO, QT_ABSTENCAO, QT_COMPARECIMENTO_DEFICIENCIA, QT_ABSTENCAO_DEFICIENCIA, QT_COMPARECIMENTO_TTE, QT_ABSTENCAO_TTE, QT_COMPAREC_FACULTATIVO, QT_ABST_FACULTATIVO, QT_COMPAREC_OBRIGATORIO, QT_ABST_OBRIGATORIO, QT_COMPAREC_DEFIC_FACULTATIVO, QT_ABST_DEFIC_FACULTATIVO, QT_COMPAREC_DEFIC_OBRIGATORIO, QT_ABST_DEFIC_OBRIGATORIO] │ [VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR] │ false     │
└──────────┴─────────┴───────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────┘

In [ ]:
con.sql("SELECT DISTINCT DT_GERACAO FROM dados").df()

         DT_GERACAO
0        29/04/2025
1        29/04/2025
2        29/04/2025
3        29/04/2025
4        29/04/2025
...             ...
9825472  29/04/2025
9825473  29/04/2025
9825474  29/04/2025
9825475  29/04/2025
9825476  29/04/2025

[9825477 rows x 1 columns]